CREATE DATABASE ZAZUSR;





CREATE TABLE PRODUCTOS (
   	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    CANTIDAD INT(100),
    TALLA VARCHAR(10),
    COLOR VARCHAR(15) NOT NULL,
    PRECIO INT(10),
    EXTENSIONES VARCHAR (100),
    PUBLICADO_EN_INSTA VARCHAR(2),
     PUBLICADO_EN_WWW VARCHAR(2),
     ESTADO_DEL_PRODUCTO VARCHAR(20),
     CALIDAD(10)
);

/*
CREATE TABLE employees (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    salary INT(10) NOT NULL
);*/